### ISSUE TITLE
If Document changed isn't subscribed don't take the hit to lookup the original document

### ISSUE THREAD

**Issue by niemyjski** [FoundatioFx/Foundatio.Repositories#20]
We need to ensure though that this doesn't affect cache invalidation.

**Comment by niemyjski** [comment]
@ejsmith trying to decide if this is still actionable.

**Comment by ejsmith** [comment]
I think we talked about it and determined it’s a bad idea. There could be method overloads that are looking at the value that we don’t know about. Also, users have the option to turn it off at repo level.
